[build]
  command = "echo 'No se requiere comando de construcción'"
  publish = "."
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200